apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: mutating-webhook
  labels:
    component: mutating-controller
webhooks:
- admissionReviewVersions:
  - v1
  name: test.example.com
  failurePolicy: Fail
  clientConfig:
    url: "https://10.0.2.15:443/mutate/deployments"
    # service:
    #   name: controller-service
    #   namespace: default
    #   path: /mutate/deployments
    # caBundle: <redacted> # a base64 encoded self signed ca cert is needed because all Admission Webhooks need to be on SSL
    caBundle: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUM5RENDQWR5Z0F3SUJBZ0lSQUtoUHh5VWowZkdlb09mSWFQcGxuaEF3RFFZSktvWklodmNOQVFFTEJRQXcKRlRFVE1CRUdBMVVFQXhNS2EzVmlaWEp1WlhSbGN6QWVGdzB5TkRBMU1qa3dORFEwTXpCYUZ3MHlOREE1TURZdwpORFEwTXpCYU1BNHhEREFLQmdOVkJBTVRBMjVoYlRDQ0FTSXdEUVlKS29aSWh2Y05BUUVCQlFBRGdnRVBBRENDCkFRb0NnZ0VCQU5yUWFyQXM4UXcrYXVScmVSUzBOSE9kelJVZGUzTTd3MXJNT3NXejAySEFnazYrMmdBL2dJTEMKV3JtWEo2UE9rVGdoc2Y0TDBRSWV0TXFJTTFyY0crRDRYaW5YbDBJVEVTamVPU2dRbnJhVkNGRnNHKzlRblcvSApuanNPMVlpaExTclVMVEFhZUgrWVVQSStkQXBqQk1ObmNuR25aUzR6Q0REbk1ORDJmYkc1bENUN0IreVpiRHlsCjB0ZGtITjl4UE93YjF5Y2tGRlgwdC8xMGJtQm9YRTZDUWp3U3V0OXJQdmswSWJ2WThENGZocGYvSG13Qy9vN2sKTXI0Y2lBaEExL2trQ0xGcTh5T2d5Yy9xYW45dS81cWxCMmtUTUtZS2g5eC9NVll2ZVZpQkJPM1Z3QTJjVE1YbwppUXdRS1ZYSUZGUVdpSWYveWt3c0kvcS84bFZYbVRjQ0F3RUFBYU5HTUVRd0V3WURWUjBsQkF3d0NnWUlLd1lCCkJRVUhBd0l3REFZRFZSMFRBUUgvQkFJd0FEQWZCZ05WSFNNRUdEQVdnQlFsYTVEaE42dkkya1NENk9QZVcwWXYKTmg0b3dUQU5CZ2txaGtpRzl3MEJBUXNGQUFPQ0FRRUFJWWEwQlhSa1ZWZEY0UzFOU3NUbm0xQ1JqMlozZ0JuRApOQ3l4WlNxbHdjSjdWVEdNQ0l3QmlvYUM4d0NkeE1yVUJ3S01Hd1JkeVZWVFQrSVFZQ0FVbDNhTm1SemdJMHlJCk1aemxiVWFkSExLUC9DeGx0d3VHeDIrL1dZK1ZyeWtZUytOYXBoZFZTNHQ3cHYxUGQ1QTJFYkUweTdOTVB2cDMKWWx5bGtBblVWYzRQYk0wTmRtamZTMlhPK2hvcGQ3T0plRGpvVUorL2ZuNWlxbncvSEdySitFNVdQVndEcEVoawo2RnpBSU1ZelpYemJzYzBxUm9qZWJXaWJiUlhNYlpOTnhmd1JjYnRlTFJvQmhxUjl3VHpad0svc3FVTWZ3UUI4CmRaK2RmY0lwTXNTbWxSWGhiN3V4cDhTcWJmd2ZVQVhieFlrcTJDYW1MYTdhM2NVaTB0dnFaUT09Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
  rules:  
    - apiGroups: ["apps"]
      resources:
        - "deployments"
      apiVersions:
        - "*"
      operations:
        - CREATE
  sideEffects: None